import namespace, { NamespaceBuilder } from "@rdfjs/namespace";
import { NamedNode } from "@rdfjs/types";

export interface Knextract {
  "": NamedNode<"http://purl.archive.org/purl/knextract/ontology#">;
  // // Classes
  // CompletionMessage: NamedNode<"http://purl.archive.org/purl/knextract/ontology#CompletionMessage">;
  // CompletionMessageProcessing: NamedNode<"http://purl.archive.org/purl/knextract/ontology#CompletionMessageProcessing">;
  // ConceptAnnotation: NamedNode<"http://purl.archive.org/purl/knextract/ontology#ConceptAnnotation">;
  // ConceptList: NamedNode<"http://purl.archive.org/purl/knextract/ontology#ConceptList">;
  // ConceptPath: NamedNode<"http://purl.archive.org/purl/knextract/ontology#ConceptPath">;
  // ConceptSchemeConceptSelector: NamedNode<"http://purl.archive.org/purl/knextract/ontology#ConceptSchemeConceptSelector">;
  // ConceptSchemeTopConceptSelector: NamedNode<"http://purl.archive.org/purl/knextract/ontology#ConceptSchemeTopConceptSelector">;
  // ConceptSelection: NamedNode<"http://purl.archive.org/purl/knextract/ontology#ConceptSelection">;
  // Corpus: NamedNode<"http://purl.archive.org/purl/knextract/ontology#Corpus">;
  // CorpusDeletion: NamedNode<"http://purl.archive.org/purl/knextract/ontology#CorpusDeletion">;
  // Document: NamedNode<"http://purl.archive.org/purl/knextract/ontology#Document">;
  // DocumentDeletion: NamedNode<"http://purl.archive.org/purl/knextract/ontology#DocumentDeletion">;
  // EnumeratedConceptSelector: NamedNode<"http://purl.archive.org/purl/knextract/ontology#EnumeratedConceptSelector">;
  // EveryConceptAnnotatorExecution: NamedNode<"http://purl.archive.org/purl/knextract/ontology#EveryConceptAnnotatorExecution">;
  // EveryConceptAnnotatorParameters: NamedNode<"http://purl.archive.org/purl/knextract/ontology#EveryConceptAnnotatorParameters">;
  // Exception: NamedNode<"http://purl.archive.org/purl/knextract/ontology#Exception">;
  // GoldAnnotation: NamedNode<"http://purl.archive.org/purl/knextract/ontology#GoldAnnotation">;
  // InferredAnnotation: NamedNode<"http://purl.archive.org/purl/knextract/ontology#InferredAnnotation">;
  // LanguageModelConceptAnnotatorExecution: NamedNode<"http://purl.archive.org/purl/knextract/ontology#LanguageModelConceptAnnotatorExecution">;
  // LanguageModelConceptAnnotatorParameters: NamedNode<"http://purl.archive.org/purl/knextract/ontology#LanguageModelConceptAnnotatorParameters">;
  // LanguageModelInvocation: NamedNode<"http://purl.archive.org/purl/knextract/ontology#LanguageModelInvocation">;
  // LiteralPromptInputValue: NamedNode<"http://purl.archive.org/purl/knextract/ontology#LiteralPromptInputValue">;
  // NarrowerConceptSelector: NamedNode<"http://purl.archive.org/purl/knextract/ontology#NarrowerConceptSelector">;
  // NarrowerTransitiveConceptSelector: NamedNode<"http://purl.archive.org/purl/knextract/ontology#NarrowerTransitiveConceptSelector">;
  // Prompt: NamedNode<"http://purl.archive.org/purl/knextract/ontology#Prompt">;
  // PromptConstruction: NamedNode<"http://purl.archive.org/purl/knextract/ontology#PromptConstruction">;
  // PromptMessage: NamedNode<"http://purl.archive.org/purl/knextract/ontology#PromptMessage">;
  // PromptMessageList: NamedNode<"http://purl.archive.org/purl/knextract/ontology#PromptMessageList">;
  // PromptMessageTemplate: NamedNode<"http://purl.archive.org/purl/knextract/ontology#PromptMessageTemplate">;
  // PromptMessageTemplateList: NamedNode<"http://purl.archive.org/purl/knextract/ontology#PromptMessageTemplateList">;
  // PromptTemplate: NamedNode<"http://purl.archive.org/purl/knextract/ontology#PromptTemplate">;
  // RecursiveConceptAnnotatorExecution: NamedNode<"http://purl.archive.org/purl/knextract/ontology#RecursiveConceptAnnotatorExecution">;
  // SparqlSelectPromptInputValue: NamedNode<"http://purl.archive.org/purl/knextract/ontology#SparqlSelectPromptInputValue">;
  // TextualEntity: NamedNode<"http://purl.archive.org/purl/knextract/ontology#TextualEntity">;
  // Title: NamedNode<"http://purl.archive.org/purl/knextract/ontology#Title">;
  // Workflow: NamedNode<"http://purl.archive.org/purl/knextract/ontology#Workflow">;
  // WorkflowConceptAnnotatorStep: NamedNode<"http://purl.archive.org/purl/knextract/ontology#WorkflowConceptAnnotatorStep">;
  // WorkflowConceptAnnotatorStepExecution: NamedNode<"http://purl.archive.org/purl/knextract/ontology#WorkflowConceptAnnotatorStepExecution">;
  // WorkflowDeletion: NamedNode<"http://purl.archive.org/purl/knextract/ontology#WorkflowDeletion">;
  // WorkflowExecution: NamedNode<"http://purl.archive.org/purl/knextract/ontology#WorkflowExecution">;
  // WorkflowSuperStep: NamedNode<"http://purl.archive.org/purl/knextract/ontology#WorkflowSuperStep">;
  // WorkflowSuperStepExecution: NamedNode<"http://purl.archive.org/purl/knextract/ontology#WorkflowSuperStepExecution">;
  // // Properties
  answer: NamedNode<"http://purl.archive.org/purl/knextract/ontology#answer">;
  claims: NamedNode<"http://purl.archive.org/purl/knextract/ontology#claims">;
  // completionMessageProcessing: NamedNode<"http://purl.archive.org/purl/knextract/ontology#completionMessageProcessing">;
  // conceptAnnotatorExecution: NamedNode<"http://purl.archive.org/purl/knextract/ontology#conceptAnnotatorExecution">;
  // conceptAnnotatorParameters: NamedNode<"http://purl.archive.org/purl/knextract/ontology#conceptAnnotatorParameters">;
  // conceptSelection: NamedNode<"http://purl.archive.org/purl/knextract/ontology#conceptSelection">;
  // conceptSelector: NamedNode<"http://purl.archive.org/purl/knextract/ontology#conceptSelector">;
  deleted: NamedNode<"http://purl.archive.org/purl/knextract/ontology#deleted">;
  // encodingType: NamedNode<"http://purl.archive.org/purl/knextract/ontology#encodingType">;
  // endedAtTime: NamedNode<"http://purl.archive.org/purl/knextract/ontology#endedAtTime">;
  // exception: NamedNode<"http://purl.archive.org/purl/knextract/ontology#exception">;
  // exceptionMessage: NamedNode<"http://purl.archive.org/purl/knextract/ontology#exceptionMessage">;
  // focusConcept: NamedNode<"http://purl.archive.org/purl/knextract/ontology#focusConcept">;
  // generatedAnnotation: NamedNode<"http://purl.archive.org/purl/knextract/ontology#generatedAnnotation">;
  // generatedCompletionMessage: NamedNode<"http://purl.archive.org/purl/knextract/ontology#generatedCompletionMessage">;
  // generatedConceptList: NamedNode<"http://purl.archive.org/purl/knextract/ontology#generatedConceptList">;
  // generatedPrompt: NamedNode<"http://purl.archive.org/purl/knextract/ontology#generatedPrompt">;
  gold: NamedNode<"http://purl.archive.org/purl/knextract/ontology#gold">;
  // ignored: NamedNode<"http://purl.archive.org/purl/knextract/ontology#ignored">;
  // languageModel: NamedNode<"http://purl.archive.org/purl/knextract/ontology#languageModel">;
  // languageModelInvocation: NamedNode<"http://purl.archive.org/purl/knextract/ontology#languageModelInvocation">;
  // literalForm: NamedNode<"http://purl.archive.org/purl/knextract/ontology#literalForm">;
  memberOfCorpus: NamedNode<"http://purl.archive.org/purl/knextract/ontology#memberOfCorpus">;
  // mutable: NamedNode<"http://purl.archive.org/purl/knextract/ontology#mutable">;
  // object: NamedNode<"http://purl.archive.org/purl/knextract/ontology#object">;
  // precedes: NamedNode<"http://purl.archive.org/purl/knextract/ontology#precedes">;
  // priority: NamedNode<"http://purl.archive.org/purl/knextract/ontology#priority">;
  // private: NamedNode<"http://purl.archive.org/purl/knextract/ontology#private">;
  processInput: NamedNode<"http://purl.archive.org/purl/knextract/ontology#processInput">;
  processOutput: NamedNode<"http://purl.archive.org/purl/knextract/ontology#processOutput">;
  // promptConstruction: NamedNode<"http://purl.archive.org/purl/knextract/ontology#promptConstruction">;
  // promptInputValue: NamedNode<"http://purl.archive.org/purl/knextract/ontology#promptInputValue">;
  // promptMessageRole: NamedNode<"http://purl.archive.org/purl/knextract/ontology#promptMessageRole">;
  // promptMessageTemplates: NamedNode<"http://purl.archive.org/purl/knextract/ontology#promptMessageTemplates">;
  // promptMessages: NamedNode<"http://purl.archive.org/purl/knextract/ontology#promptMessages">;
  // promptTemplate: NamedNode<"http://purl.archive.org/purl/knextract/ontology#promptTemplate">;
  questionnaireAdministration: NamedNode<"http://purl.archive.org/purl/knextract/ontology#questionnaireAdministration">;
  questionnaireAdministrations: NamedNode<"http://purl.archive.org/purl/knextract/ontology#questionnaireAdministrations">;
  // recursive: NamedNode<"http://purl.archive.org/purl/knextract/ontology#recursive">;
  // sparqlSelect: NamedNode<"http://purl.archive.org/purl/knextract/ontology#sparqlSelect">;
  // startedAtTime: NamedNode<"http://purl.archive.org/purl/knextract/ontology#startedAtTime">;
  subProcesses: NamedNode<"http://purl.archive.org/purl/knextract/ontology#subProcesses">;
  // subject: NamedNode<"http://purl.archive.org/purl/knextract/ontology#subject">;
  // terminology: NamedNode<"http://purl.archive.org/purl/knextract/ontology#terminology">;
  // terminus: NamedNode<"http://purl.archive.org/purl/knextract/ontology#terminus">;
  // textualEntity: NamedNode<"http://purl.archive.org/purl/knextract/ontology#textualEntity">;
  // title: NamedNode<"http://purl.archive.org/purl/knextract/ontology#title">;
  // url: NamedNode<"http://purl.archive.org/purl/knextract/ontology#url">;
  // usedAnnotatorParameters: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedAnnotatorParameters">;
  // usedCompletionMessage: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedCompletionMessage">;
  // usedConceptList: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedConceptList">;
  // usedConceptSelector: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedConceptSelector">;
  // usedCorpus: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedCorpus">;
  // usedDocument: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedDocument">;
  // usedPrompt: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedPrompt">;
  // usedPromptTemplate: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedPromptTemplate">;
  // usedWorkflow: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedWorkflow">;
  // usedWorkflowStep: NamedNode<"http://purl.archive.org/purl/knextract/ontology#usedWorkflowStep">;
  // variable: NamedNode<"http://purl.archive.org/purl/knextract/ontology#variable">;
  workflow: NamedNode<"http://purl.archive.org/purl/knextract/ontology#workflow">;
  // workflowStep: NamedNode<"http://purl.archive.org/purl/knextract/ontology#workflowStep">;
  // workflowStepExecution: NamedNode<"http://purl.archive.org/purl/knextract/ontology#workflowStepExecution">;
  workflowStepExecutions: NamedNode<"http://purl.archive.org/purl/knextract/ontology#workflowStepExecutions">;
}

const builder = namespace(
  "http://purl.archive.org/purl/knextract/ontology#",
) as any;
export const strict = builder as NamespaceBuilder<keyof Knextract> & Knextract;
export const loose = builder as NamespaceBuilder & Knextract;
