name: Continuous Integration
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22
      - run: npm ci
      - uses: actions/cache@v4
        name: Cache .next/cache
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-${{ hashFiles('app/**/*.ts', 'app/**/*.tsx', 'lib/**/*.ts', 'lib/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json') }}-
      - run: script/cibuild
        env:
          NODE_OPTIONS: "--max-old-space-size=5120"
#      - if: always()
#        uses:  davelosert/vitest-coverage-report-action@v2
#        with:
#          file-coverage-mode: "all"
#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps
#      - name: Run Playwright tests
#        run: npx playwright test
#      - uses: actions/upload-artifact@v4
#        if: always()
#        with:
#          name: playwright-report
#          path: playwright-report/
#          retention-days: 30
